### ISSUE TITLE
Model.json is not available anymore

### ISSUE THREAD

**Issue by yannklein** [jmlb/insight_project#4]
We cannot access to your model.json anymore. I guess that you closed the TensorJS project you created for it (cf https://storage.googleapis.com/modelinsight/tfjs/model.json).
Would you mind sharing it somewhere in the repo for us to use it?

**Comment by chrisgh1** [comment]
Has anyone had any luck getting the model.json?  Or has anyone been successful with creating a new model?

**Comment by maxencedouet** [comment]
Has anyone had any luck getting the model.json? Didn't manage yet ...

**Comment by jmlb** [comment]
sorry for the late reply. the link to model.json is fixed: https://storage.googleapis.com/modelinsight/tfjs/model.json
